version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    entrypoint: "bash -c 'sleep 3 && npm start'"
    env_file:
      - .env
  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
