version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: isbushcar/devops-for-programmers-project-lvl1
    entrypoint: "npm test"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}


