name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
      POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
    steps:
      - uses: actions/checkout@v3
      - run: 'echo $POSTGRES_PASSWORD >> .env && echo $POSTGRES_USER >> .env && echo $POSTGRES_DB >> .env && make ci'
      - run: make ci

  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-for-programmers-project-lvl1:latest
          file: "./Dockerfile.production"
    needs: test